# permissions for end users to edit secretgencontrollerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretgencontrollerconfig-editor-role
rules:
- apiGroups:
  - addons.tanzu.vmware.com
  resources:
  - secretgencontrollerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.tanzu.vmware.com
  resources:
  - secretgencontrollerconfigs/status
  verbs:
  - get
