#@ load("@ytt:data", "data")
---
apiVersion: cni.tanzu.vmware.com/v1alpha1
kind: AntreaConfig
metadata:
  name: #@ data.values.TKR_VERSION
  namespace: #@ data.values.GLOBAL_NAMESPACE
spec:
  antrea:
    config:
      featureGates:
        EndpointSlice: true
---
apiVersion: cni.tanzu.vmware.com/v1alpha1
kind: AntreaConfig
metadata:
  name: #@ "{}-routable".format(data.values.TKR_VERSION)
  namespace: #@ data.values.GLOBAL_NAMESPACE
spec:
  antrea:
    config:
      trafficEncapMode: "noEncap"
      noSNAT: true
      featureGates:
        AntreaProxy: true
        EndpointSlice: true
