#@ load("@ytt:data", "data")
---
apiVersion: cni.tanzu.vmware.com/v1alpha1
kind: CalicoConfig
metadata:
  name: #@ data.values.TKR_VERSION
  namespace: #@ data.values.GLOBAL_NAMESPACE
spec:
  calico:
    config:
      vethMTU: 0 #! This is the only available parameter. Even thought the value is the same as default, keeping it here because spec can't be empty
